builders:
  hive_generator:
    import: "package:hive_generator_io/hive_generator_io.dart"
    builder_factories: ["getBuilder"]
    build_extensions: { ".dart": ["hive_generator_io.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
