name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 1.0.0
publish_to: none

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter

  hive:
    path: ../hive
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  test: ^1.26.3
  mockito: ^5.5.1
  build_runner: ^2.8.0
