name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 1.2.0
publish_to: none

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter

  hive:
    path: ../hive
  path: ^1.9.1
  path_provider: ^2.1.5


dev_dependencies:
  build_runner: ^2.10.1
  lint: ^2.8.0
  mockito: ^5.5.1
  test: ^1.26.3
