name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 1.0.0
publish_to: none

environment:
  sdk: "^3.4.0"

dependencies:
  flutter:
    sdk: flutter

  hive:
    path: ../hive
  path_provider: ^2.0.10
  path: ^1.8.2

dev_dependencies:
  test: ^1.21.1
  mockito: ^5.2.0
  build_runner: ^2.1.11
