include: package:lint/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: false
    constant_identifier_names: false
    parameter_assignments: false
